[project]
name = "day3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nitin Mehra", email = "145772092+nitinmehra09@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "groq>=1.7.0",
    "numpy>=2.5.3",
    "python-dotenv>=1.2.4",
    "sentence-transformers>=6.1.0",
]

[project.scripts]
day3 = "day3:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
